channels:
- conda-forge
dependencies:
- python=3.10.18
- pip<=25.2
- pip:
  - mlflow==2.14.1
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==24.2
  - pandas==2.2.2
  - pyyaml==6.0.3
  - scikit-learn==1.4.2
  - scipy==1.15.3
  - xgboost==2.0.3
name: mlflow-env
